
    let News =[
        {id:"1", 
        img: require('../image/LongCovid.png'), 
        head:"Understanding Long Covid",
        title:"We know more now than before, and it’s still alarming" ,
        paragra:"By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.",
        date:{day:"9", month:"Dec", year : "2023"}, 
        isTrending : false, 
        category:"Writing", 
        read:"9 min read",
        save: false,
        createdUser:{ Name:"Dr. Tom Frieden", userId:"1", img:require('../image/profile.png') ,organization :""} 
        },
        {id:"2", 
        img:require('../image/News2.png'), 
        head:"Braiding Past into Future",
        title:"Nican Huehcatlahtolli, a New Futurism", 
        paragra:"By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.",
        date:{day:"9", month:"Dec", year : "2022"}, 
        isTrending : true, 
        category:"Machine Learning", 
        read:"11 min read",
        save: false,
        createdUser:{ Name:"David Bowles", userId:"2", img:require('../image/profile.png') ,organization :""} 
        },
        {id:"3", 
        img:require('../image/News3.png'), 
        head:"Learning to Cope with Estrangement: When Children “Cancel” Their Parents",
        title:"An estranged father reflects on the stigma and surprising prevalence of these family rifts.", 
        paragra:"By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.",
        date:{day:"9", month:"Dec", year : "2022"}, 
        isTrending : true, 
        category:"Relationships", 
        read:"6 min read",
        save: false,
        createdUser:{ Name:"Ed Erginziger", userId:"3", img:require('../image/profile.png'), organization :"  Invisible Illness"} 
        },
        {id:"4", 
        img:require('../image/News4.png'), 
        head:"ChatGPT Is Having a Thomas Edison Moment",
        title:"Why breakthrough technologies need to be accessible", 
        paragra:"By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.",
        date:{day:"9", month:"Dec", year : "2022"}, 
        isTrending : true, 
        category:"Technology", 
        read:"4 min read",
        save: false,
        createdUser:{ Name:"Thomas Smith", userId:"4", img:require('../image/profile.png') ,organization :""} 
        },
        {id:"5", 
        img:require('../image/News5.png'), 
        head:" Spotify’s Year-End Lists Are the Ultimate Personality Test",
        title:"Why the mass sharing of the music streaming service’s year-end lists is uniquely telling", 
        paragra:"By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.",
        date:{day:"6", month:"Dec", year : "2019"} ,
        isTrending : true, 
        category:"Productivity", 
        read:"3 min read",
        save: false,
        createdUser:{ Name:"Allegra Hobbs", userId:"5", img:require('../image/profile.png') ,organization :" Forge"} 
        },
        {id:"6", 
        img:require('../image/News6.png'), 
        head:"Why Your Team Needs a Weekly Metrics Review",
        title:"What is it, how you can start, and why it will make your product team much better builders and collaborators.", 
        paragra:"By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.",
        date:{day:"30", month:"Nov", year : "2022"}, 
        isTrending : true, 
        category:"Productivity", 
        read:"7 min read",
        save: false,
        createdUser:{ Name:"Julie Zhou ", userId:"5", img:require('../image/profile.png') ,organization :""} 
        },
        {id:"7", 
        img:require('../image/News7.png'), 
        head:"Tyrion Lannister and The 7 Habits of Highly Effective People",
        title:"A Game of Thrones-themed synopsis of The 7 Habits of Highly Effective People", 
        paragra:"By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.",
        date:{day:"2", month:"Dec", year : "2022"}, 
        isTrending : true, 
        category:"Self Improvement", 
        read:"7 min read",
        save: false,
        createdUser:{ Name:"Elliot Graebert", userId:"6", img:require('../image/profile.png') ,organization :""} 
        },
        {id:"8", 
        img:require('../image/News8.png'), 
        head:"Microdosing, Mastodon, and Jonah Hill.",
        title:"Seeking peace, finding kindness.", 
        paragra:"By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.",
        date:{day:"30", month:"Nov", year : "2022"}, 
        isTrending : false, 
        category:"Data Science", 
        read:"8 min read",
        save: false,
        createdUser:{ Name:"Mindy Stern", userId:"7", img:require('../image/profile.png') ,organization :" Thoughts And Ideas"} 
        },
        {id:"9", 
        img:require('../image/News9.png'), 
        head:"What if failure is the plan?",
        title:"I’ve been thinking a lot about failure lately. Failure comes in many forms, but I’m especially interested in situations in which people…", 
        paragra:"By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.By now you’ve likely heard of ChatGPT, the open AI chatbot that seemingly does everything from being able to write code, write essays for high school students, content for websites, or even explain the James Webb Telescope while pretending to be Bodhi from Point Break.",
        date:{day:"5", month:"Dec", year : "2022"}, 
        isTrending : true, 
        category:"Self Improvement", 
        read:"14 min read",
        save: false,
        createdUser:{ Name:"danah boyd", userId:"7", img:require('../image/profile.png') ,organization :""} 
        },
      ]

export  default News